type: object
description: A metadataset providing details on the provider of this OOAPI implementation
required:
  - contactEmail
  - specification
properties:
  contactEmail:
    type: string
    description: Contact e-mail address of the service owner
    format: email
    maxLength: 256
    example: admin@universiteitvanharderwijk.nl
  specification:
    type: string
    description: URL of the API specification (YAML or JSON, compliant with [Open API Specification v3](https://github.com/OAI/OpenAPI-Specification/))
    format: uri
    maxLength: 2048
    example: https://rawgit.com/open-education-api/specification/v3/docs.html#tag/course-offerings/paths/~1course-offerings/get
  documentation:
    type:
      - string
      - 'null'
    description: URL of the API documentation, including general terms and privacy statement
    format: uri
    maxLength: 2048
    example: https://open-education-api.github.io/specification/v4/docs.html
  supportedConsumers:
    type:
      - array
      - 'null'
    items:
      type: object
      description: Object for communicating data to a specific consumer (destination). This object has no relationship with the consumer query parameter.
      required:
        - consumerKey
        - version
      properties:
        consumerKey:
          description: The key of the consumer (destination) for which this information is intended. See the consumer registry for more information.
          type: string
          example: "nl-test-admin"
        version:
          description: the version number of this consumer
          type: string
          example: "0.9.3"
  supportedOperations:
    type:
      - array
      - 'null'
    items:
      type: object
      description: Object for communicating VERBS and endpoints that are supported by this implementation.
      required:
        - verb
        - path
      properties:
        verbs:
          type: array
          description: The type of method or verb.
          items:
            type: string
            enum:
            - GET
            - PUT
            - PATCH
            - POST
            example: "GET"
        path:
          description: the path of the operation
          type: string
          format: uri-reference
          example: "/courses"
  supportedExpands:
    type: array
    items:
      type: object
      description: Object for communicating the expands and paths for which they are implemented.
      required:
      - expandableObject
      - path
      properties:
        expandableObjects:
          description: the objects that are expandable for a specific path
          type: array
          items:
            $ref: '../enumerations/expandableObjects.yaml'
        path:
          description: the path of the operation
          type: string
          format: uri-reference
          example: "/courses"
  ext:
    oneOf:
      - $ref: './Ext.yaml'
      - type: 'null'
